### ISSUE TITLE
Bad magic number

### ISSUE THREAD

**Issue by zwep** [gpilab/philips-data-reader#12]
Hi, I get the following import errors when using ANY release given in this repo. I am currently working with Ubuntu 16.04, Python 3.6 and PyQt version 5.9.

I have tried all morning to find out what is wrong.. and why it is acting this way. But I really have no idea. It seems that the .pyc are compiled under a different Python version than the one I am using.

Could you elaborate on this?

Below is the error import

Fri Sep 27 10:48:06 2019 - gpi.config:450 - WARNING - User Config: 'PATH::LIB_DIRS': '/home/bugger/bin/gpilab_install/envs/gpi/lib/python3.7/site-packages' is not a directory.
Fri Sep 27 10:48:06 2019 - gpi.config:420 - ---- - /home/bugger/.gpirc has been loaded.
QApplication: invalid style override passed, ignoring it.
Fri Sep 27 10:48:06 2019 - gpi.loader:140 - ERROR - /home/bugger/gpi/philips/fileIO/GPI/ReadPhilips_GPI.pyc module failed to load in loadMod('compiled') with:
Traceback (most recent call last):
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/site-packages/gpi/loader.py", line 138, in loadMod
    mod = imp.load_compiled(store_name, fullpath, fp)
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/imp.py", line 192, in load_compiled
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in '/home/bugger/gpi/philips/fileIO/GPI/ReadPhilips_GPI': b'\x16\r\r\n'

Fri Sep 27 10:48:06 2019 - gpi.library:208 - ERROR - Module not loadable, skipping. (/home/bugger/gpi/philips/fileIO/GPI/ReadPhilips_GPI.pyc)
Fri Sep 27 10:48:06 2019 - gpi.loader:140 - ERROR - /home/bugger/gpi/philips_7_7/fileIO/GPI/ReadPhilips_GPI.pyc module failed to load in loadMod('compiled') with:
Traceback (most recent call last):
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/site-packages/gpi/loader.py", line 138, in loadMod
    mod = imp.load_compiled(store_name, fullpath, fp)
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/imp.py", line 192, in load_compiled
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in '/home/bugger/gpi/philips_7_7/fileIO/GPI/ReadPhilips_GPI': b'\x16\r\r\n'

Fri Sep 27 10:48:06 2019 - gpi.library:208 - ERROR - Module not loadable, skipping. (/home/bugger/gpi/philips_7_7/fileIO/GPI/ReadPhilips_GPI.pyc)
Fri Sep 27 10:48:06 2019 - gpi.loader:140 - ERROR - /home/bugger/gpi/philips_4_3/fileIO/GPI/ReadPhilips_GPI.pyc module failed to load in loadMod('compiled') with:
Traceback (most recent call last):
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/site-packages/gpi/loader.py", line 138, in loadMod
    mod = imp.load_compiled(store_name, fullpath, fp)
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/imp.py", line 192, in load_compiled
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in '/home/bugger/gpi/philips_4_3/fileIO/GPI/ReadPhilips_GPI': b'\x03\xf3\r\n'

Fri Sep 27 10:48:06 2019 - gpi.library:208 - ERROR - Module not loadable, skipping. (/home/bugger/gpi/philips_4_3/fileIO/GPI/ReadPhilips_GPI.pyc)
Fri Sep 27 10:48:06 2019 - gpi.loader:140 - ERROR - /home/bugger/gpi/philips_6_2/fileIO/GPI/ReadPhilips_GPI.pyc module failed to load in loadMod('compiled') with:
Traceback (most recent call last):
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/site-packages/gpi/loader.py", line 138, in loadMod
    mod = imp.load_compiled(store_name, fullpath, fp)
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/imp.py", line 192, in load_compiled
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in '/home/bugger/gpi/philips_6_2/fileIO/GPI/ReadPhilips_GPI': b'\x16\r\r\n'

Fri Sep 27 10:48:06 2019 - gpi.library:208 - ERROR - Module not loadable, skipping. (/home/bugger/gpi/philips_6_2/fileIO/GPI/ReadPhilips_GPI.pyc)
Fri Sep 27 10:48:06 2019 - gpi.loader:140 - ERROR - /home/bugger/gpi/philips_5_11/fileIO/GPI/ReadPhilips_GPI.pyc module failed to load in loadMod('compiled') with:
Traceback (most recent call last):
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/site-packages/gpi/loader.py", line 138, in loadMod
    mod = imp.load_compiled(store_name, fullpath, fp)
  File "/home/bugger/miniconda3/envs/gpi/lib/python3.6/imp.py", line 192, in load_compiled
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 888, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
ImportError: bad magic number in '/home/bugger/gpi/philips_5_11/fileIO/GPI/ReadPhilips_GPI': b'\x16\r\r\n'

**Comment by aganders3** [comment]
This is due to using a different version of Python compared to what the node was originally compiled with. If you are covered by a Philips NDA I suggest contacting your Clinical Scientist to try to get a copy of the source code for this node library. It's difficult to troubleshoot these binary distribution problems.

Otherwise perhaps @borupdaniel or @rkrobison could compile a new version for you. Unfortunately I no longer have access to the source code for this node myself.

**Comment by zwep** [comment]
Can you tell me which version of Python is required for these nodes? Based on the magic numbers that are unique to each python distro, my guess would be something like 3.5.2...

Another problem that comes with this is that the new GPI version requires Python version 3.6 or 3.7.. which seems to make it in any way incompatible with these nodes. Do you know which version of GPI is supported by the Python version that is linked to this node?

**Comment by aganders3** [comment]
This has been a problem with the binary release for a while - unfortunately I don't know which version of Python corresponds to each release but my guess would also be 3.5.x based on age of the builds, etc.

With the new version of GPI requiring 3.6+ someone will need to recompile the binary release. @sandeepganji may also be able to help with this - I was working on compiling multiple versions of this node with him before I left Philips.

**Comment by sandeepganji** [comment]
Hi,
If tell me the version of python you are using I will post that release
compiled code.
Sandeep

**Comment by zwep** [comment]
Hi @sandeepganji 

for completeness, both Python version 3.6.x and 3.7.x would be helpful.

~Seb

**Comment by sandeepganji** [comment]
posted the Python 3.6 linux version at
https://github.com/gpilab/philips-data-reader/releases/tag/v1.0.4

**Comment by zwep** [comment]
Thanks, everything works
